name: Deploy to VM

on:
  push:
    branches:
      - deploy_docker  # Trigger only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test:coverage
      
      - name: Build application
        run: npm run build
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker using ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: fiardiel
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/fiardiel/budidayaplus_fe:latest .
          docker push ghcr.io/fiardiel/budidayaplus_fe:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Run this job only after the build job completes successfully

    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: DOCKER_IMAGE=ghcr.io/fiardiel/budidayaplus_fe:latest

          script: |
            docker pull $DOCKER_IMAGE
            docker stop budidayaplus_fe || true
            docker rm budidayaplus_fe || true
            docker run -d --name budidayaplus_fe -p 3000:3000 $DOCKER_IMAGE
